<meta charset="UTF-8">
<title>La Padua Pizzeria</title>
<meta http-equiv="X-UA-Compatible" content="IE-edge">
<meta name="viewport" content="widht-device-widht, initial-scale=1, maximum-scale=1">
<meta name="keywords" content="Comida merida, pizza, hamburgesas, hotdogs.">
<meta name="description" content="Expertos en hacer la mejor pizza de todo el mundo">
<meta name="author" content="Luis Javier Martinez Fernandez">
<link rel="shortcut icon" href="IMG/logito.png" type="image/x-icon">

<link rel="stylesheet" href="CSS/fuentes.css">
<link rel="stylesheet" href="CSS/icomoon.css">
<link rel="stylesheet" href="CSS/normalize.css">
<link rel="stylesheet" href="CSS/hamburgers.css">
<link rel="stylesheet" href="CSS/style.css">